/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.0.2-48-gfdb8746532"
#endif /* AVUTIL_FFVERSION_H */
